### ISSUE TITLE
Why does autocut open the cash drawer, is it possible to disable that?

### ISSUE THREAD

**Issue by satur9nine** [star-micronics/StarPRNT-SDK-Android-Java#16]
## Description
When I execute the following code the printer will cut paper and then open the cash drawer:

```
        StarIoExt.Emulation emulation = ModelCapability.getEmulation(ModelCapability.SP700);
        ICommandBuilder builder = StarIoExt.createCommandBuilder(emulation);
        builder.appendCutPaper(ICommandBuilder.CutPaperAction.PartialCutWithFeed);
        byte[] cutCommand = builder.getCommands();
        port.writePort(cutCommand, 0, cutCommand.length);
```

But I do not want to open the cash drawer every time paper is cut.

I checked the programmer manual and memory switch settings but I do not see a way to prevent cutting from opening the cash drawer, is it possible, how?

## Your device where the bug occurs 
Android Pixel 7

## Your printer
- Model Names: SP700
- Firmware Version: V2.1.0
- Interface: Ethernet

## Your development environment
Linux 6.5.0-28-generic #29~22.04.1-Ubuntu

**Comment by bandit-ibayashi** [comment]
@satur9nine I assume that this issue is caused by the printer setting. Perhaps there is a bit standing for some reason outside of the published items in the memory switch.

Would it be possible to install the following Windows tool to initialize the memory switch of your SP700 to the factory defaults and set it up again?
https://starmicronics.com/support/download/starprnt-intelligence-software-full/

We are afraid to bother you, but thank you in advance.

**Comment by satur9nine** [comment]
This appears to have worked, I am surprised there are secret bits like this.
