### ISSUE TITLE
Doesn't print, only cuts the paper (TSP100III)

### ISSUE THREAD

**Issue by sharpwitz** [star-micronics/StarPRNT-SDK-Android-Java#2]
We are able to print via TCP to most Star printers.  However, when we switched over to Bluetooth for the TSP100iiiBi, we were unable to print to the printer.  When a print request is sent, the printer will cut the paper only.  We believe we have paired successfully to this printer.  We also attempted to use the StarGraphic emulation but perhaps we didn't code it correctly?

Please advise.

Is the TSP100iiiBi not supported by this SDK?
Is the SP700 not supported by this SDK?

**Comment by gare-bear** [comment]
@sharpwitz All the printers you've mentioned are supported by this SDK. My educated guess tells me your receipts are text-based and for that reason nothing is printing on the TSP100III series. All printers equipped with a cutter support the cut command so this would also reinforce that theory.

The TSP100III series are raster-only. In order to print, you must send your receipt as a raster graphic/bitmap. You're using the correct emulation but the payload is wrong.

**Comment by sharpwitz** [comment]
is there an example receipt code instead of just Hello World?

https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/android_java/en/api_starioext_i_command_builder.html?highlight=bitmap#icommandbuilder-appendbitmap

**Comment by sharpwitz** [comment]
We are going to answer our own question here with Bluetooth connection.  
Use port name "BT:"

This will only work with the library 2.2.0 or newer

We are using StarIoExtManager (of starioextension library) v 1.15.0. 
com.starmicronics:stario library of version 2.9.0 is on the classpath

We got the TSP100 and SP700 printers to print via bluetooth with this solution.
